export const direcciones = [
  {id: 1, DetalleDireccion: 'Finland'},
  {id: 2, DetalleDireccion: 'Indonesia'},
  {id: 3, DetalleDireccion: 'China'},
  {id: 4, DetalleDireccion: 'Latvia'},
  {id: 5, DetalleDireccion: 'Cameroon'},
  {id: 6, DetalleDireccion: 'Vietnam'},
  {id: 7, DetalleDireccion: 'Guatemala'},
  {id: 8, DetalleDireccion: 'Nigeria'},
  {id: 9, DetalleDireccion: 'China'},
  {id: 10, DetalleDireccion: 'Chile'},
  {id: 11, DetalleDireccion: 'Portugal'},
  {id: 12, DetalleDireccion: 'Thailand'},
  {id: 13, DetalleDireccion: 'Syria'},
  {id: 14, DetalleDireccion: 'Philippines'},
  {id: 15, DetalleDireccion: 'Indonesia'},
  {id: 16, DetalleDireccion: 'Indonesia'},
  {id: 17, DetalleDireccion: 'Sweden'},
  {id: 18, DetalleDireccion: 'China'},
  {id: 19, DetalleDireccion: 'Thailand'},
  {id: 20, DetalleDireccion: 'China'},
  {id: 21, DetalleDireccion: 'Brazil'},
  {id: 22, DetalleDireccion: 'Guatemala'},
  {id: 23, DetalleDireccion: 'Thailand'},
  {id: 24, DetalleDireccion: 'Brazil'},
  {id: 25, DetalleDireccion: 'South Africa'},
  {id: 26, DetalleDireccion: 'South Africa'},
  {id: 27, DetalleDireccion: 'Indonesia'},
  {id: 28, DetalleDireccion: 'Pakistan'},
  {id: 29, DetalleDireccion: 'Iran'},
  {id: 30, DetalleDireccion: 'Russia'},
  {id: 31, DetalleDireccion: 'Indonesia'},
  {id: 32, DetalleDireccion: 'Netherlands'},
  {id: 33, DetalleDireccion: 'Russia'},
  {id: 34, DetalleDireccion: 'Albania'},
  {id: 35, DetalleDireccion: 'Bolivia'},
  {id: 36, DetalleDireccion: 'Mauritius'},
  {id: 37, DetalleDireccion: 'Peru'},
  {id: 38, DetalleDireccion: 'China'},
  {id: 39, DetalleDireccion: 'China'},
  {id: 40, DetalleDireccion: 'Colombia'},
  {id: 41, DetalleDireccion: 'Poland'},
  {id: 42, DetalleDireccion: 'Albania'},
  {id: 43, DetalleDireccion: 'Poland'},
  {id: 44, DetalleDireccion: 'Brazil'},
  {id: 45, DetalleDireccion: 'South Korea'},
  {id: 46, DetalleDireccion: 'Indonesia'},
  {id: 47, DetalleDireccion: 'Croatia'},
  {id: 48, DetalleDireccion: 'China'},
  {id: 49, DetalleDireccion: 'Iran'},
  {id: 50, DetalleDireccion: 'Argentina'},

];
