// Generated by https://quicktype.io

export interface Compra {
  id: number;
  idCompra: number;
  idProducto: number;
  nombreProducto: string;
  presentacion: string;
  urlImage: string;
  precioActual: number;
  totalProducto: number;
  descuento: number;
  subTotal:number;
}
