// Generated by https://quicktype.io

export interface PaginationResponse<T> {
  count: number;
  pageIndex: number;
  pageSize: number;
  data: T;
  pageCount: 10 | 20 | 26 | 50;
  search: string;
}

export interface PaginationRequest {
  search?: string;
  sort?: string;
  pageIndex: number;
  pageSize: number;
}
